apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
